/**
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 * 🔮 Sanskrit Grammar - PWA Service Worker Registration
 * ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 * Registers the service worker generated by vite-plugin-pwa.
 * Handles update detection and reload prompting.
 * Ensures the app is fully installable as a standalone PWA.
 */

/**
 * Register the PWA Service Worker
 * This function is called from main.jsx on app initialization.
 */
export const registerPWA = () => {
  // Only register in production or if SW is supported
  if (!('serviceWorker' in navigator)) {
    console.info('[PWA] Service Workers are not supported in this browser.');
    return;
  }

  // Wait until the page has fully loaded before registering SW
  window.addEventListener('load', async () => {
    try {
      const registration = await navigator.serviceWorker.register('/sw.js', {
        scope: '/'
      });

      console.info('[PWA] Service Worker registered successfully.');

      // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      // Handle SW Updates
      // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      registration.addEventListener('updatefound', () => {
        const newWorker = registration.installing;

        if (!newWorker) return;

        newWorker.addEventListener('statechange', () => {
          if (newWorker.state === 'installed') {
            if (navigator.serviceWorker.controller) {
              // A new version is available
              console.info('[PWA] New version available. Prompting user to update.');
              showUpdateNotification();
            } else {
              // First install — app is now available offline
              console.info('[PWA] App is now available offline.');
            }
          }
        });
      });

      // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      // Periodic check for updates (every 60 minutes)
      // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      setInterval(() => {
        registration.update().catch((error) => {
          console.warn('[PWA] Update check failed:', error);
        });
      }, 60 * 60 * 1000);

    } catch (error) {
      console.error('[PWA] Service Worker registration failed:', error);
    }
  });

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Handle controller changes (when new SW takes over)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  let refreshing = false;
  navigator.serviceWorker.addEventListener('controllerchange', () => {
    if (refreshing) return;
    refreshing = true;
    window.location.reload();
  });
};

/**
 * Shows a non-intrusive update notification bar at the top of the screen.
 * When clicked, it tells the new SW to skip waiting and take over.
 */
const showUpdateNotification = () => {
  // Create the notification element
  const notification = document.createElement('div');
  notification.id = 'pwa-update-notification';
  notification.innerHTML = `
    <div style="
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      z-index: 100000;
      background: linear-gradient(135deg, #d35400 0%, #a04000 100%);
      color: #fdf5e6;
      padding: 12px 16px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      font-family: 'Inter', sans-serif;
      font-size: 14px;
      box-shadow: 0 4px 15px rgba(0,0,0,0.3);
      animation: slideDown 0.4s ease-out;
    ">
      <span>🔮 A new version is available!</span>
      <button id="pwa-update-btn" style="
        background: rgba(255,255,255,0.2);
        border: 1px solid rgba(255,255,255,0.4);
        color: #fdf5e6;
        padding: 6px 16px;
        border-radius: 9999px;
        font-size: 13px;
        font-weight: 600;
        cursor: pointer;
        font-family: 'Inter', sans-serif;
      ">Update</button>
    </div>
    <style>
      @keyframes slideDown {
        from { transform: translateY(-100%); opacity: 0; }
        to { transform: translateY(0); opacity: 1; }
      }
    </style>
  `;

  document.body.appendChild(notification);

  // Handle click — tell SW to skip waiting
  const updateBtn = document.getElementById('pwa-update-btn');
  if (updateBtn) {
    updateBtn.addEventListener('click', () => {
      if (navigator.serviceWorker.controller) {
        navigator.serviceWorker.controller.postMessage({ type: 'SKIP_WAITING' });
      }
      // Remove the notification
      notification.remove();
    });
  }

  // Auto-dismiss after 15 seconds if user doesn't interact
  setTimeout(() => {
    if (document.getElementById('pwa-update-notification')) {
      notification.style.transition = 'opacity 0.4s ease-out';
      notification.style.opacity = '0';
      setTimeout(() => notification.remove(), 400);
    }
  }, 15000);
};
